import styles from './summarizedText.module.css'
export default function SummarizedText() {

    return (
    <p className={styles.summarizedText}>
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    THIS IS THE TEXT THAT HAS BEEN SUMMARIZED <br />
    </p>)
}